### ISSUE TITLE
What's the good way to test sandbox application ?

### ISSUE THREAD

**Issue by Kwadz** [alexandre-melard/jquery-file-upload-sandbox#1]
Hi,
This sandbox is a very good idea to show how to use the bundle.

However when I try to test it, after a composer update and the web folder creation, I have this page wherein file and multi files upload is not possible.

![jQuery-file-upload-screenshot](https://f.cloud.github.com/assets/1472599/41949/fa6c1eca-55f3-11e2-8d20-3b638f9b0da7.png)

Could you give me advise on appropriate way to use your bundle.

Many thanks !

**Comment by alexandre-melard** [comment]
I think the problem is whith your local server, you should use vhost and direct the docroot to the web folder of the sandbox. Did you use vagrant ?

**Comment by Kwadz** [comment]
Close as obsolete
